[project]
name = "cerebro-okr"
version = "0.1.0"
description = "OKR management system to KPIs for a 360 degree goals and performance management system for a Product & Services company"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]",
    "psycopg2>=2.9.10",
    "psycopg2-binary",
    "pydantic",
    "python-dotenv",
    "sqlalchemy",
    "toml>=0.10.2",
    "uvicorn[standard]",
]

# [tool.uv]
# dev = "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
# seed = "python app/seed.py"
# serve = "serve -s dist -l 3000"
